#!/bin/sh
#
# Configure options script for re-calling MagickCore compilation options
# required to use the MagickCore library.
#

prefix=/usr
exec_prefix=${prefix}

usage="\
Usage: Magick-config [--cflags] [--cppflags] [--exec-prefix] [--ldflags] [--libs] [--prefix] [--version]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      echo "Example: gcc \`Magick-config --cflags --cppflags\` -o core core.c \`Magick-config --ldflags --libs\`" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
  esac
  case $1 in
    --prefix=*)
      prefix=$optarg
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo '6.9.11-60 Q16 '
      ;;
    --cflags)
      /usr/bin/pkg-config --cflags MagickCore
      ;;
    --cxxflags)
      /usr/bin/pkg-config --cflags MagickCore
      ;;
    --cppflags)
      /usr/bin/pkg-config --cflags MagickCore
      ;;
    --ldflags)
      /usr/bin/pkg-config --libs MagickCore
      ;;
    --libs)
      /usr/bin/pkg-config --libs MagickCore
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
